title: 创意实验 | 析构理想
email: wdqjj@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lab.idealdestructor.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Ideal Destructor # add your name
author-pic: francis.jpg
about-author: My name is Deqiang Wang. I’m a Front-end developer graduated from Nankai university, majoring in computer science. And I'm also an amateur producer of Dark Glitch-hop and Synthwave music who loves astronomy and history.

# Contact links
email: wdqjj@qq.com
phone: +86 
website: idealdestructor.com
linkedin: 德强-王-a18742122
github: idealdestructor # Add your Github handle
twitter: idealdestructor # Add your Twitter handle
facebook: idealdestructor
instagram: idealdestructor
pinterest: idealdestructor

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: ~IDEAL() # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
